#/bin/bash
set -euxo pipefail

# Split 1
mxfold2 predict --model MixC --gpu 0 --entity=andrewjung --project=rnasdb --group=mxfold2 --job_type=rnasdb_weighted --param model-nr7dvzcr:v0 --bpp /home/andrew.jung/rna_sdb/scripts/training/mxfold2/mxfold2_rnasdb_archiveII_split_1_pred.1.pq /home/andrew.jung/rna_sdb/scripts/training/mxfold2/mxfold2_rnasdb_archiveII_split_1.pq
mxfold2 predict --model MixC --gpu 0 --entity=andrewjung --project=rnasdb --group=mxfold2 --job_type=rnasdb_weighted --param model-4s4cfptq:v0 --bpp /home/andrew.jung/rna_sdb/scripts/training/mxfold2/mxfold2_rnasdb_archiveII_split_1_pred.2.pq /home/andrew.jung/rna_sdb/scripts/training/mxfold2/mxfold2_rnasdb_archiveII_split_1.pq
mxfold2 predict --model MixC --gpu 0 --entity=andrewjung --project=rnasdb --group=mxfold2 --job_type=rnasdb_weighted --param model-x1yu4x8q:v0 --bpp /home/andrew.jung/rna_sdb/scripts/training/mxfold2/mxfold2_rnasdb_archiveII_split_1_pred.3.pq /home/andrew.jung/rna_sdb/scripts/training/mxfold2/mxfold2_rnasdb_archiveII_split_1.pq

mxfold2 predict --model MixC --gpu 0 --entity=andrewjung --project=rnasdb --group=mxfold2 --job_type=rnasdb_weighted --param model-nr7dvzcr:v0 --bpp /home/andrew.jung/rna_sdb/scripts/training/mxfold2/mxfold2_rnasdb_test_split_1_pred.1.pq /home/andrew.jung/rna_sdb/scripts/training/mxfold2/mxfold2_rnasdb_test_split_1_0.025.pq
mxfold2 predict --model MixC --gpu 0 --entity=andrewjung --project=rnasdb --group=mxfold2 --job_type=rnasdb_weighted --param model-4s4cfptq:v0 --bpp /home/andrew.jung/rna_sdb/scripts/training/mxfold2/mxfold2_rnasdb_test_split_1_pred.2.pq /home/andrew.jung/rna_sdb/scripts/training/mxfold2/mxfold2_rnasdb_test_split_1_0.025.pq
mxfold2 predict --model MixC --gpu 0 --entity=andrewjung --project=rnasdb --group=mxfold2 --job_type=rnasdb_weighted --param model-x1yu4x8q:v0 --bpp /home/andrew.jung/rna_sdb/scripts/training/mxfold2/mxfold2_rnasdb_test_split_1_pred.3.pq /home/andrew.jung/rna_sdb/scripts/training/mxfold2/mxfold2_rnasdb_test_split_1_0.025.pq

# Split 2
mxfold2 predict --model MixC --gpu 0 --entity=andrewjung --project=rnasdb --group=mxfold2 --job_type=rnasdb_weighted --param model-h6pjag92:v0 --bpp /home/andrew.jung/rna_sdb/scripts/training/mxfold2/mxfold2_rnasdb_archiveII_split_2_pred.1.pq /home/andrew.jung/rna_sdb/scripts/training/mxfold2/mxfold2_rnasdb_archiveII_split_2.pq
mxfold2 predict --model MixC --gpu 0 --entity=andrewjung --project=rnasdb --group=mxfold2 --job_type=rnasdb_weighted --param model-f33ay146:v0 --bpp /home/andrew.jung/rna_sdb/scripts/training/mxfold2/mxfold2_rnasdb_archiveII_split_2_pred.2.pq /home/andrew.jung/rna_sdb/scripts/training/mxfold2/mxfold2_rnasdb_archiveII_split_2.pq
mxfold2 predict --model MixC --gpu 0 --entity=andrewjung --project=rnasdb --group=mxfold2 --job_type=rnasdb_weighted --param model-u05eppml:v0 --bpp /home/andrew.jung/rna_sdb/scripts/training/mxfold2/mxfold2_rnasdb_archiveII_split_2_pred.3.pq /home/andrew.jung/rna_sdb/scripts/training/mxfold2/mxfold2_rnasdb_archiveII_split_2.pq

mxfold2 predict --model MixC --gpu 0 --entity=andrewjung --project=rnasdb --group=mxfold2 --job_type=rnasdb_weighted --param model-h6pjag92:v0 --bpp /home/andrew.jung/rna_sdb/scripts/training/mxfold2/mxfold2_rnasdb_test_split_2_pred.1.pq /home/andrew.jung/rna_sdb/scripts/training/mxfold2/mxfold2_rnasdb_test_split_2_0.1.pq
mxfold2 predict --model MixC --gpu 0 --entity=andrewjung --project=rnasdb --group=mxfold2 --job_type=rnasdb_weighted --param model-f33ay146:v0 --bpp /home/andrew.jung/rna_sdb/scripts/training/mxfold2/mxfold2_rnasdb_test_split_2_pred.2.pq /home/andrew.jung/rna_sdb/scripts/training/mxfold2/mxfold2_rnasdb_test_split_2_0.1.pq
mxfold2 predict --model MixC --gpu 0 --entity=andrewjung --project=rnasdb --group=mxfold2 --job_type=rnasdb_weighted --param model-u05eppml:v0 --bpp /home/andrew.jung/rna_sdb/scripts/training/mxfold2/mxfold2_rnasdb_test_split_2_pred.3.pq /home/andrew.jung/rna_sdb/scripts/training/mxfold2/mxfold2_rnasdb_test_split_2_0.1.pq

# Split 3
mxfold2 predict --model MixC --gpu 0 --entity=andrewjung --project=rnasdb --group=mxfold2 --job_type=rnasdb_weighted --param model-w92ymuo6:v0 --bpp /home/andrew.jung/rna_sdb/scripts/training/mxfold2/mxfold2_rnasdb_archiveII_split_3_pred.1.pq /home/andrew.jung/rna_sdb/scripts/training/mxfold2/mxfold2_rnasdb_archiveII_split_3.pq
mxfold2 predict --model MixC --gpu 0 --entity=andrewjung --project=rnasdb --group=mxfold2 --job_type=rnasdb_weighted --param model-ql5wpxpv:v0 --bpp /home/andrew.jung/rna_sdb/scripts/training/mxfold2/mxfold2_rnasdb_archiveII_split_3_pred.2.pq /home/andrew.jung/rna_sdb/scripts/training/mxfold2/mxfold2_rnasdb_archiveII_split_3.pq
mxfold2 predict --model MixC --gpu 0 --entity=andrewjung --project=rnasdb --group=mxfold2 --job_type=rnasdb_weighted --param model-8iw9diy3:v0 --bpp /home/andrew.jung/rna_sdb/scripts/training/mxfold2/mxfold2_rnasdb_archiveII_split_3_pred.3.pq /home/andrew.jung/rna_sdb/scripts/training/mxfold2/mxfold2_rnasdb_archiveII_split_3.pq

mxfold2 predict --model MixC --gpu 0 --entity=andrewjung --project=rnasdb --group=mxfold2 --job_type=rnasdb_weighted --param model-w92ymuo6:v0 --bpp /home/andrew.jung/rna_sdb/scripts/training/mxfold2/mxfold2_rnasdb_test_split_3_pred.1.pq /home/andrew.jung/rna_sdb/scripts/training/mxfold2/mxfold2_rnasdb_test_split_3_0.1.pq
mxfold2 predict --model MixC --gpu 0 --entity=andrewjung --project=rnasdb --group=mxfold2 --job_type=rnasdb_weighted --param model-ql5wpxpv:v0 --bpp /home/andrew.jung/rna_sdb/scripts/training/mxfold2/mxfold2_rnasdb_test_split_3_pred.2.pq /home/andrew.jung/rna_sdb/scripts/training/mxfold2/mxfold2_rnasdb_test_split_3_0.1.pq
mxfold2 predict --model MixC --gpu 0 --entity=andrewjung --project=rnasdb --group=mxfold2 --job_type=rnasdb_weighted --param model-8iw9diy3:v0 --bpp /home/andrew.jung/rna_sdb/scripts/training/mxfold2/mxfold2_rnasdb_test_split_3_pred.3.pq /home/andrew.jung/rna_sdb/scripts/training/mxfold2/mxfold2_rnasdb_test_split_3_0.1.pq

# Split 4
mxfold2 predict --model MixC --gpu 0 --entity=andrewjung --project=rnasdb --group=mxfold2 --job_type=rnasdb_weighted --param model-p3dphi6v:v0 --bpp /home/andrew.jung/rna_sdb/scripts/training/mxfold2/mxfold2_rnasdb_archiveII_split_4_pred.1.pq /home/andrew.jung/rna_sdb/scripts/training/mxfold2/mxfold2_rnasdb_archiveII_split_4.pq
mxfold2 predict --model MixC --gpu 0 --entity=andrewjung --project=rnasdb --group=mxfold2 --job_type=rnasdb_weighted --param model-o0vdyoaf:v0 --bpp /home/andrew.jung/rna_sdb/scripts/training/mxfold2/mxfold2_rnasdb_archiveII_split_4_pred.2.pq /home/andrew.jung/rna_sdb/scripts/training/mxfold2/mxfold2_rnasdb_archiveII_split_4.pq
mxfold2 predict --model MixC --gpu 0 --entity=andrewjung --project=rnasdb --group=mxfold2 --job_type=rnasdb_weighted --param model-g1vdxwin:v0 --bpp /home/andrew.jung/rna_sdb/scripts/training/mxfold2/mxfold2_rnasdb_archiveII_split_4_pred.3.pq /home/andrew.jung/rna_sdb/scripts/training/mxfold2/mxfold2_rnasdb_archiveII_split_4.pq

mxfold2 predict --model MixC --gpu 0 --entity=andrewjung --project=rnasdb --group=mxfold2 --job_type=rnasdb_weighted --param model-p3dphi6v:v0 --bpp /home/andrew.jung/rna_sdb/scripts/training/mxfold2/mxfold2_rnasdb_test_split_4_pred.1.pq /home/andrew.jung/rna_sdb/scripts/training/mxfold2/mxfold2_rnasdb_test_split_4_0.1.pq
mxfold2 predict --model MixC --gpu 0 --entity=andrewjung --project=rnasdb --group=mxfold2 --job_type=rnasdb_weighted --param model-o0vdyoaf:v0 --bpp /home/andrew.jung/rna_sdb/scripts/training/mxfold2/mxfold2_rnasdb_test_split_4_pred.2.pq /home/andrew.jung/rna_sdb/scripts/training/mxfold2/mxfold2_rnasdb_test_split_4_0.1.pq
mxfold2 predict --model MixC --gpu 0 --entity=andrewjung --project=rnasdb --group=mxfold2 --job_type=rnasdb_weighted --param model-g1vdxwin:v0 --bpp /home/andrew.jung/rna_sdb/scripts/training/mxfold2/mxfold2_rnasdb_test_split_4_pred.3.pq /home/andrew.jung/rna_sdb/scripts/training/mxfold2/mxfold2_rnasdb_test_split_4_0.1.pq

# Split 5
mxfold2 predict --model MixC --gpu 0 --entity=andrewjung --project=rnasdb --group=mxfold2 --job_type=rnasdb_weighted --param model-7uzxt3zr:v0 --bpp /home/andrew.jung/rna_sdb/scripts/training/mxfold2/mxfold2_rnasdb_archiveII_split_5_pred.1.pq /home/andrew.jung/rna_sdb/scripts/training/mxfold2/mxfold2_rnasdb_archiveII_split_5.pq
mxfold2 predict --model MixC --gpu 0 --entity=andrewjung --project=rnasdb --group=mxfold2 --job_type=rnasdb_weighted --param model-tzhqnukb:v0 --bpp /home/andrew.jung/rna_sdb/scripts/training/mxfold2/mxfold2_rnasdb_archiveII_split_5_pred.2.pq /home/andrew.jung/rna_sdb/scripts/training/mxfold2/mxfold2_rnasdb_archiveII_split_5.pq
mxfold2 predict --model MixC --gpu 0 --entity=andrewjung --project=rnasdb --group=mxfold2 --job_type=rnasdb_weighted --param model-p3q0npkk:v0 --bpp /home/andrew.jung/rna_sdb/scripts/training/mxfold2/mxfold2_rnasdb_archiveII_split_5_pred.3.pq /home/andrew.jung/rna_sdb/scripts/training/mxfold2/mxfold2_rnasdb_archiveII_split_5.pq

mxfold2 predict --model MixC --gpu 0 --entity=andrewjung --project=rnasdb --group=mxfold2 --job_type=rnasdb_weighted --param model-7uzxt3zr:v0 --bpp /home/andrew.jung/rna_sdb/scripts/training/mxfold2/mxfold2_rnasdb_test_split_5_pred.1.pq /home/andrew.jung/rna_sdb/scripts/training/mxfold2/mxfold2_rnasdb_test_split_5_0.1.pq
mxfold2 predict --model MixC --gpu 0 --entity=andrewjung --project=rnasdb --group=mxfold2 --job_type=rnasdb_weighted --param model-tzhqnukb:v0 --bpp /home/andrew.jung/rna_sdb/scripts/training/mxfold2/mxfold2_rnasdb_test_split_5_pred.2.pq /home/andrew.jung/rna_sdb/scripts/training/mxfold2/mxfold2_rnasdb_test_split_5_0.1.pq
mxfold2 predict --model MixC --gpu 0 --entity=andrewjung --project=rnasdb --group=mxfold2 --job_type=rnasdb_weighted --param model-p3q0npkk:v0 --bpp /home/andrew.jung/rna_sdb/scripts/training/mxfold2/mxfold2_rnasdb_test_split_5_pred.3.pq /home/andrew.jung/rna_sdb/scripts/training/mxfold2/mxfold2_rnasdb_test_split_5_0.1.pq

# Split 6
mxfold2 predict --model MixC --gpu 0 --entity=andrewjung --project=rnasdb --group=mxfold2 --job_type=rnasdb_weighted --param model-noqqjhzn:v0 --bpp /home/andrew.jung/rna_sdb/scripts/training/mxfold2/mxfold2_rnasdb_archiveII_split_6_pred.1.pq /home/andrew.jung/rna_sdb/scripts/training/mxfold2/mxfold2_rnasdb_archiveII_split_6.pq
mxfold2 predict --model MixC --gpu 0 --entity=andrewjung --project=rnasdb --group=mxfold2 --job_type=rnasdb_weighted --param model-pnrni9sc:v0 --bpp /home/andrew.jung/rna_sdb/scripts/training/mxfold2/mxfold2_rnasdb_archiveII_split_6_pred.2.pq /home/andrew.jung/rna_sdb/scripts/training/mxfold2/mxfold2_rnasdb_archiveII_split_6.pq
mxfold2 predict --model MixC --gpu 0 --entity=andrewjung --project=rnasdb --group=mxfold2 --job_type=rnasdb_weighted --param model-duqyijgg:v0 --bpp /home/andrew.jung/rna_sdb/scripts/training/mxfold2/mxfold2_rnasdb_archiveII_split_6_pred.3.pq /home/andrew.jung/rna_sdb/scripts/training/mxfold2/mxfold2_rnasdb_archiveII_split_6.pq

mxfold2 predict --model MixC --gpu 0 --entity=andrewjung --project=rnasdb --group=mxfold2 --job_type=rnasdb_weighted --param model-noqqjhzn:v0 --bpp /home/andrew.jung/rna_sdb/scripts/training/mxfold2/mxfold2_rnasdb_test_split_6_pred.1.pq /home/andrew.jung/rna_sdb/scripts/training/mxfold2/mxfold2_rnasdb_test_split_6_0.1.pq
mxfold2 predict --model MixC --gpu 0 --entity=andrewjung --project=rnasdb --group=mxfold2 --job_type=rnasdb_weighted --param model-pnrni9sc:v0 --bpp /home/andrew.jung/rna_sdb/scripts/training/mxfold2/mxfold2_rnasdb_test_split_6_pred.2.pq /home/andrew.jung/rna_sdb/scripts/training/mxfold2/mxfold2_rnasdb_test_split_6_0.1.pq
mxfold2 predict --model MixC --gpu 0 --entity=andrewjung --project=rnasdb --group=mxfold2 --job_type=rnasdb_weighted --param model-duqyijgg:v0 --bpp /home/andrew.jung/rna_sdb/scripts/training/mxfold2/mxfold2_rnasdb_test_split_6_pred.3.pq /home/andrew.jung/rna_sdb/scripts/training/mxfold2/mxfold2_rnasdb_test_split_6_0.1.pq

# Split 7
mxfold2 predict --model MixC --gpu 0 --entity=andrewjung --project=rnasdb --group=mxfold2 --job_type=rnasdb_weighted --param model-qitc30uy:v0 --bpp /home/andrew.jung/rna_sdb/scripts/training/mxfold2/mxfold2_rnasdb_archiveII_split_7_pred.1.pq /home/andrew.jung/rna_sdb/scripts/training/mxfold2/mxfold2_rnasdb_archiveII_split_7.pq
mxfold2 predict --model MixC --gpu 0 --entity=andrewjung --project=rnasdb --group=mxfold2 --job_type=rnasdb_weighted --param model-ebsy9gfc:v0 --bpp /home/andrew.jung/rna_sdb/scripts/training/mxfold2/mxfold2_rnasdb_archiveII_split_7_pred.2.pq /home/andrew.jung/rna_sdb/scripts/training/mxfold2/mxfold2_rnasdb_archiveII_split_7.pq
mxfold2 predict --model MixC --gpu 0 --entity=andrewjung --project=rnasdb --group=mxfold2 --job_type=rnasdb_weighted --param model-ldl21724:v0 --bpp /home/andrew.jung/rna_sdb/scripts/training/mxfold2/mxfold2_rnasdb_archiveII_split_7_pred.3.pq /home/andrew.jung/rna_sdb/scripts/training/mxfold2/mxfold2_rnasdb_archiveII_split_7.pq

mxfold2 predict --model MixC --gpu 0 --entity=andrewjung --project=rnasdb --group=mxfold2 --job_type=rnasdb_weighted --param model-qitc30uy:v0 --bpp /home/andrew.jung/rna_sdb/scripts/training/mxfold2/mxfold2_rnasdb_test_split_7_pred.1.pq /home/andrew.jung/rna_sdb/scripts/training/mxfold2/mxfold2_rnasdb_test_split_7_0.1.pq
mxfold2 predict --model MixC --gpu 0 --entity=andrewjung --project=rnasdb --group=mxfold2 --job_type=rnasdb_weighted --param model-ebsy9gfc:v0 --bpp /home/andrew.jung/rna_sdb/scripts/training/mxfold2/mxfold2_rnasdb_test_split_7_pred.2.pq /home/andrew.jung/rna_sdb/scripts/training/mxfold2/mxfold2_rnasdb_test_split_7_0.1.pq
mxfold2 predict --model MixC --gpu 0 --entity=andrewjung --project=rnasdb --group=mxfold2 --job_type=rnasdb_weighted --param model-ldl21724:v0 --bpp /home/andrew.jung/rna_sdb/scripts/training/mxfold2/mxfold2_rnasdb_test_split_7_pred.3.pq /home/andrew.jung/rna_sdb/scripts/training/mxfold2/mxfold2_rnasdb_test_split_7_0.1.pq

# Split 8
mxfold2 predict --model MixC --gpu 0 --entity=andrewjung --project=rnasdb --group=mxfold2 --job_type=rnasdb_weighted --param model-a0gslnre:v0 --bpp /home/andrew.jung/rna_sdb/scripts/training/mxfold2/mxfold2_rnasdb_archiveII_split_8_pred.1.pq /home/andrew.jung/rna_sdb/scripts/training/mxfold2/mxfold2_rnasdb_archiveII_split_8.pq
mxfold2 predict --model MixC --gpu 0 --entity=andrewjung --project=rnasdb --group=mxfold2 --job_type=rnasdb_weighted --param model-cytngrn4:v0 --bpp /home/andrew.jung/rna_sdb/scripts/training/mxfold2/mxfold2_rnasdb_archiveII_split_8_pred.2.pq /home/andrew.jung/rna_sdb/scripts/training/mxfold2/mxfold2_rnasdb_archiveII_split_8.pq
mxfold2 predict --model MixC --gpu 0 --entity=andrewjung --project=rnasdb --group=mxfold2 --job_type=rnasdb_weighted --param model-iit2zl88:v0 --bpp /home/andrew.jung/rna_sdb/scripts/training/mxfold2/mxfold2_rnasdb_archiveII_split_8_pred.3.pq /home/andrew.jung/rna_sdb/scripts/training/mxfold2/mxfold2_rnasdb_archiveII_split_8.pq

mxfold2 predict --model MixC --gpu 0 --entity=andrewjung --project=rnasdb --group=mxfold2 --job_type=rnasdb_weighted --param model-a0gslnre:v0 --bpp /home/andrew.jung/rna_sdb/scripts/training/mxfold2/mxfold2_rnasdb_test_split_8_pred.1.pq /home/andrew.jung/rna_sdb/scripts/training/mxfold2/mxfold2_rnasdb_test_split_8_0.1.pq
mxfold2 predict --model MixC --gpu 0 --entity=andrewjung --project=rnasdb --group=mxfold2 --job_type=rnasdb_weighted --param model-cytngrn4:v0 --bpp /home/andrew.jung/rna_sdb/scripts/training/mxfold2/mxfold2_rnasdb_test_split_8_pred.2.pq /home/andrew.jung/rna_sdb/scripts/training/mxfold2/mxfold2_rnasdb_test_split_8_0.1.pq
mxfold2 predict --model MixC --gpu 0 --entity=andrewjung --project=rnasdb --group=mxfold2 --job_type=rnasdb_weighted --param model-iit2zl88:v0 --bpp /home/andrew.jung/rna_sdb/scripts/training/mxfold2/mxfold2_rnasdb_test_split_8_pred.3.pq /home/andrew.jung/rna_sdb/scripts/training/mxfold2/mxfold2_rnasdb_test_split_8_0.1.pq