# lightning.pytorch==2.2.3
fit:
  trainer:
    callbacks: 
      - class_path: lightning.pytorch.callbacks.ModelSummary
        init_args:
          max_depth: 3
      - class_path: lightning.pytorch.callbacks.EarlyStopping
        init_args:
          monitor: val/f1
          patience: 20
          verbose: True
          mode: max
      - class_path: lightning.pytorch.callbacks.ModelCheckpoint
        init_args:
          save_top_k: 1
          monitor: val/f1
          mode: max
          save_last: False
          verbose: True
    max_epochs: 60
    limit_train_batches: 337 # effective number of samples per epoch = 10,784 (32 * 337) which matches with bpRNA-TR0
    limit_val_batches: 0.1
    use_distributed_sampler: False
    logger:
      - class_path: lightning.pytorch.loggers.WandbLogger
        init_args:
          group: ufold
          log_model: True
    # Override defaults for callbacks
    enable_model_summary: False
  model:
    class_path: rna_sdb.models.ufold.UFoldTrainer
    init_args:
      conv_filters: [16, 32, 64, 128, 256] # reduce the number of filters to match the size of ResNet
      threshold: 0.5
  data:
    class_path: rna_sdb.data.RNASDBDatasetModule
    init_args:
      batch_size: 32
      test_batch_size: 1
      max_seq_len: 450
      num_workers: 12
      support_ufold: True
  optimizer:
    class_path: torch.optim.Adam
    init_args: 
      lr: 0.005
  # Custom configs
  checkpoint_prefix: rnasdb_ufold
test:
  trainer:
    logger:
      - class_path: lightning.pytorch.loggers.WandbLogger
        init_args:
          group: ufold
          log_model: False
    callbacks: 
      - class_path: lightning.pytorch.callbacks.ModelSummary
        init_args:
          max_depth: 3
    use_distributed_sampler: False
    limit_test_batches: 1.0
    # Override defaults for callbacks
    enable_model_summary: False
  model:
    class_path: rna_sdb.models.ufold.UFoldTrainer
    init_args:
      conv_filters: [16, 32, 64, 128, 256] # reduce the number of filters to match the size of ResNet
      threshold: 0.5
  data:
    class_path: rna_sdb.data.RNASDBDatasetModule
    init_args:
      batch_size: 1
      test_batch_size: 1
      num_workers: 12
      max_seq_len: 450
      support_ufold: True
  # Custom configs
  checkpoint_prefix: rnasdb_ufold_eval
