#!/bin/bash
set -euo pipefail

python run_train_rnasdb.py --config=config_ufold.yml test --wandb_config=config_wandb.yml --wandb_jobtype=archiveII --data=rna_sdb.data.ArchiveIIDatasetModule --data.support_ufold=True --data.num_workers=12 --trainer.limit_train_batches=1.0 --trainer.limit_val_batches=1.0 --data.batch_size=1 --data.split_name='split_1' --ckpt_path='../../results/saved_models/archiveII_ufold/ufold_archiveII_split_1.0.ckpt'
python run_train_rnasdb.py --config=config_ufold.yml test --wandb_config=config_wandb.yml --wandb_jobtype=archiveII --data=rna_sdb.data.ArchiveIIDatasetModule --data.support_ufold=True --data.num_workers=12 --trainer.limit_train_batches=1.0 --trainer.limit_val_batches=1.0 --data.batch_size=1 --data.split_name='split_1' --ckpt_path='../../results/saved_models/archiveII_ufold/ufold_archiveII_split_1.1.ckpt'

python run_train_rnasdb.py --config=config_ufold.yml test --wandb_config=config_wandb.yml --wandb_jobtype=archiveII --data=rna_sdb.data.ArchiveIIDatasetModule --data.support_ufold=True --data.num_workers=12 --trainer.limit_train_batches=1.0 --trainer.limit_val_batches=1.0 --data.batch_size=1 --data.split_name='split_2' --ckpt_path='../../results/saved_models/archiveII_ufold/ufold_archiveII_split_2.0.ckpt'
python run_train_rnasdb.py --config=config_ufold.yml test --wandb_config=config_wandb.yml --wandb_jobtype=archiveII --data=rna_sdb.data.ArchiveIIDatasetModule --data.support_ufold=True --data.num_workers=12 --trainer.limit_train_batches=1.0 --trainer.limit_val_batches=1.0 --data.batch_size=1 --data.split_name='split_2' --ckpt_path='../../results/saved_models/archiveII_ufold/ufold_archiveII_split_2.1.ckpt'

python run_train_rnasdb.py --config=config_ufold.yml test --wandb_config=config_wandb.yml --wandb_jobtype=archiveII --data=rna_sdb.data.ArchiveIIDatasetModule --data.support_ufold=True --data.num_workers=12 --trainer.limit_train_batches=1.0 --trainer.limit_val_batches=1.0 --data.batch_size=1 --data.split_name='split_3' --ckpt_path='../../results/saved_models/archiveII_ufold/ufold_archiveII_split_3.0.ckpt'
python run_train_rnasdb.py --config=config_ufold.yml test --wandb_config=config_wandb.yml --wandb_jobtype=archiveII --data=rna_sdb.data.ArchiveIIDatasetModule --data.support_ufold=True --data.num_workers=12 --trainer.limit_train_batches=1.0 --trainer.limit_val_batches=1.0 --data.batch_size=1 --data.split_name='split_3' --ckpt_path='../../results/saved_models/archiveII_ufold/ufold_archiveII_split_3.1.ckpt'

python run_train_rnasdb.py --config=config_ufold.yml test --wandb_config=config_wandb.yml --wandb_jobtype=archiveII --data=rna_sdb.data.ArchiveIIDatasetModule --data.support_ufold=True --data.num_workers=12 --trainer.limit_train_batches=1.0 --trainer.limit_val_batches=1.0 --data.batch_size=1 --data.split_name='split_4' --ckpt_path='../../results/saved_models/archiveII_ufold/ufold_archiveII_split_4.0.ckpt'
python run_train_rnasdb.py --config=config_ufold.yml test --wandb_config=config_wandb.yml --wandb_jobtype=archiveII --data=rna_sdb.data.ArchiveIIDatasetModule --data.support_ufold=True --data.num_workers=12 --trainer.limit_train_batches=1.0 --trainer.limit_val_batches=1.0 --data.batch_size=1 --data.split_name='split_4' --ckpt_path='../../results/saved_models/archiveII_ufold/ufold_archiveII_split_4.1.ckpt'

python run_train_rnasdb.py --config=config_ufold.yml test --wandb_config=config_wandb.yml --wandb_jobtype=archiveII --data=rna_sdb.data.ArchiveIIDatasetModule --data.support_ufold=True --data.num_workers=12 --trainer.limit_train_batches=1.0 --trainer.limit_val_batches=1.0 --data.batch_size=1 --data.split_name='split_5' --ckpt_path='../../results/saved_models/archiveII_ufold/ufold_archiveII_split_5.0.ckpt'
python run_train_rnasdb.py --config=config_ufold.yml test --wandb_config=config_wandb.yml --wandb_jobtype=archiveII --data=rna_sdb.data.ArchiveIIDatasetModule --data.support_ufold=True --data.num_workers=12 --trainer.limit_train_batches=1.0 --trainer.limit_val_batches=1.0 --data.batch_size=1 --data.split_name='split_5' --ckpt_path='../../results/saved_models/archiveII_ufold/ufold_archiveII_split_5.1.ckpt'

python run_train_rnasdb.py --config=config_ufold.yml test --wandb_config=config_wandb.yml --wandb_jobtype=archiveII --data=rna_sdb.data.ArchiveIIDatasetModule --data.support_ufold=True --data.num_workers=12 --trainer.limit_train_batches=1.0 --trainer.limit_val_batches=1.0 --data.batch_size=1 --data.split_name='split_6' --ckpt_path='../../results/saved_models/archiveII_ufold/ufold_archiveII_split_6.0.ckpt'
python run_train_rnasdb.py --config=config_ufold.yml test --wandb_config=config_wandb.yml --wandb_jobtype=archiveII --data=rna_sdb.data.ArchiveIIDatasetModule --data.support_ufold=True --data.num_workers=12 --trainer.limit_train_batches=1.0 --trainer.limit_val_batches=1.0 --data.batch_size=1 --data.split_name='split_6' --ckpt_path='../../results/saved_models/archiveII_ufold/ufold_archiveII_split_6.1.ckpt'

python run_train_rnasdb.py --config=config_ufold.yml test --wandb_config=config_wandb.yml --wandb_jobtype=archiveII --data=rna_sdb.data.ArchiveIIDatasetModule --data.support_ufold=True --data.num_workers=12 --trainer.limit_train_batches=1.0 --trainer.limit_val_batches=1.0 --data.batch_size=1 --data.split_name='split_7' --ckpt_path='../../results/saved_models/archiveII_ufold/ufold_archiveII_split_7.0.ckpt'
python run_train_rnasdb.py --config=config_ufold.yml test --wandb_config=config_wandb.yml --wandb_jobtype=archiveII --data=rna_sdb.data.ArchiveIIDatasetModule --data.support_ufold=True --data.num_workers=12 --trainer.limit_train_batches=1.0 --trainer.limit_val_batches=1.0 --data.batch_size=1 --data.split_name='split_7' --ckpt_path='../../results/saved_models/archiveII_ufold/ufold_archiveII_split_7.1.ckpt'

python run_train_rnasdb.py --config=config_ufold.yml test --wandb_config=config_wandb.yml --wandb_jobtype=archiveII --data=rna_sdb.data.ArchiveIIDatasetModule --data.support_ufold=True --data.num_workers=12 --trainer.limit_train_batches=1.0 --trainer.limit_val_batches=1.0 --data.batch_size=1 --data.split_name='split_8' --ckpt_path='../../results/saved_models/archiveII_ufold/ufold_archiveII_split_8.0.ckpt'
python run_train_rnasdb.py --config=config_ufold.yml test --wandb_config=config_wandb.yml --wandb_jobtype=archiveII --data=rna_sdb.data.ArchiveIIDatasetModule --data.support_ufold=True --data.num_workers=12 --trainer.limit_train_batches=1.0 --trainer.limit_val_batches=1.0 --data.batch_size=1 --data.split_name='split_8' --ckpt_path='../../results/saved_models/archiveII_ufold/ufold_archiveII_split_8.1.ckpt'