#!/bin/bash
set -euo pipefail

python run_train_rnasdb.py --config=config_ufold.yml fit --wandb_config=config_wandb.yml --wandb_jobtype=archiveII --data=rna_sdb.data.ArchiveIIDatasetModule --data.support_ufold=True --data.num_workers=12 --trainer.limit_train_batches=1.0 --trainer.limit_val_batches=1.0 --data.batch_size=32 --data.split_name='split_1' --data.max_seq_len=450 --seed_everything=0
python run_train_rnasdb.py --config=config_ufold.yml fit --wandb_config=config_wandb.yml --wandb_jobtype=archiveII --data=rna_sdb.data.ArchiveIIDatasetModule --data.support_ufold=True --data.num_workers=12 --trainer.limit_train_batches=1.0 --trainer.limit_val_batches=1.0 --data.batch_size=32 --data.split_name='split_1' --data.max_seq_len=450 --seed_everything=1

python run_train_rnasdb.py --config=config_ufold.yml fit --wandb_config=config_wandb.yml --wandb_jobtype=archiveII --data=rna_sdb.data.ArchiveIIDatasetModule --data.support_ufold=True --data.num_workers=12 --trainer.limit_train_batches=1.0 --trainer.limit_val_batches=1.0 --data.batch_size=32 --data.split_name='split_2' --data.max_seq_len=450 --seed_everything=0
python run_train_rnasdb.py --config=config_ufold.yml fit --wandb_config=config_wandb.yml --wandb_jobtype=archiveII --data=rna_sdb.data.ArchiveIIDatasetModule --data.support_ufold=True --data.num_workers=12 --trainer.limit_train_batches=1.0 --trainer.limit_val_batches=1.0 --data.batch_size=32 --data.split_name='split_2' --data.max_seq_len=450 --seed_everything=1

python run_train_rnasdb.py --config=config_ufold.yml fit --wandb_config=config_wandb.yml --wandb_jobtype=archiveII --data=rna_sdb.data.ArchiveIIDatasetModule --data.support_ufold=True --data.num_workers=12 --trainer.limit_train_batches=1.0 --trainer.limit_val_batches=1.0 --data.batch_size=32 --data.split_name='split_3' --data.max_seq_len=450 --seed_everything=0
python run_train_rnasdb.py --config=config_ufold.yml fit --wandb_config=config_wandb.yml --wandb_jobtype=archiveII --data=rna_sdb.data.ArchiveIIDatasetModule --data.support_ufold=True --data.num_workers=12 --trainer.limit_train_batches=1.0 --trainer.limit_val_batches=1.0 --data.batch_size=32 --data.split_name='split_3' --data.max_seq_len=450 --seed_everything=1

python run_train_rnasdb.py --config=config_ufold.yml fit --wandb_config=config_wandb.yml --wandb_jobtype=archiveII --data=rna_sdb.data.ArchiveIIDatasetModule --data.support_ufold=True --data.num_workers=12 --trainer.limit_train_batches=1.0 --trainer.limit_val_batches=1.0 --data.batch_size=32 --data.split_name='split_4' --data.max_seq_len=450 --seed_everything=0
python run_train_rnasdb.py --config=config_ufold.yml fit --wandb_config=config_wandb.yml --wandb_jobtype=archiveII --data=rna_sdb.data.ArchiveIIDatasetModule --data.support_ufold=True --data.num_workers=12 --trainer.limit_train_batches=1.0 --trainer.limit_val_batches=1.0 --data.batch_size=32 --data.split_name='split_4' --data.max_seq_len=450 --seed_everything=1

python run_train_rnasdb.py --config=config_ufold.yml fit --wandb_config=config_wandb.yml --wandb_jobtype=archiveII --data=rna_sdb.data.ArchiveIIDatasetModule --data.support_ufold=True --data.num_workers=12 --trainer.limit_train_batches=1.0 --trainer.limit_val_batches=1.0 --data.batch_size=32 --data.split_name='split_5' --data.max_seq_len=450 --seed_everything=0
python run_train_rnasdb.py --config=config_ufold.yml fit --wandb_config=config_wandb.yml --wandb_jobtype=archiveII --data=rna_sdb.data.ArchiveIIDatasetModule --data.support_ufold=True --data.num_workers=12 --trainer.limit_train_batches=1.0 --trainer.limit_val_batches=1.0 --data.batch_size=32 --data.split_name='split_5' --data.max_seq_len=450 --seed_everything=1

python run_train_rnasdb.py --config=config_ufold.yml fit --wandb_config=config_wandb.yml --wandb_jobtype=archiveII --data=rna_sdb.data.ArchiveIIDatasetModule --data.support_ufold=True --data.num_workers=12 --trainer.limit_train_batches=1.0 --trainer.limit_val_batches=1.0 --data.batch_size=32 --data.split_name='split_6' --data.max_seq_len=450 --seed_everything=0
python run_train_rnasdb.py --config=config_ufold.yml fit --wandb_config=config_wandb.yml --wandb_jobtype=archiveII --data=rna_sdb.data.ArchiveIIDatasetModule --data.support_ufold=True --data.num_workers=12 --trainer.limit_train_batches=1.0 --trainer.limit_val_batches=1.0 --data.batch_size=32 --data.split_name='split_6' --data.max_seq_len=450 --seed_everything=1

python run_train_rnasdb.py --config=config_ufold.yml fit --wandb_config=config_wandb.yml --wandb_jobtype=archiveII --data=rna_sdb.data.ArchiveIIDatasetModule --data.support_ufold=True --data.num_workers=12 --trainer.limit_train_batches=1.0 --trainer.limit_val_batches=1.0 --data.batch_size=32 --data.split_name='split_7' --data.max_seq_len=450 --seed_everything=0
python run_train_rnasdb.py --config=config_ufold.yml fit --wandb_config=config_wandb.yml --wandb_jobtype=archiveII --data=rna_sdb.data.ArchiveIIDatasetModule --data.support_ufold=True --data.num_workers=12 --trainer.limit_train_batches=1.0 --trainer.limit_val_batches=1.0 --data.batch_size=32 --data.split_name='split_7' --data.max_seq_len=450 --seed_everything=1

python run_train_rnasdb.py --config=config_ufold.yml fit --wandb_config=config_wandb.yml --wandb_jobtype=archiveII --data=rna_sdb.data.ArchiveIIDatasetModule --data.support_ufold=True --data.num_workers=12 --trainer.limit_train_batches=1.0 --trainer.limit_val_batches=1.0 --data.batch_size=32 --data.split_name='split_8' --data.max_seq_len=450 --seed_everything=0
python run_train_rnasdb.py --config=config_ufold.yml fit --wandb_config=config_wandb.yml --wandb_jobtype=archiveII --data=rna_sdb.data.ArchiveIIDatasetModule --data.support_ufold=True --data.num_workers=12 --trainer.limit_train_batches=1.0 --trainer.limit_val_batches=1.0 --data.batch_size=32 --data.split_name='split_8' --data.max_seq_len=450 --seed_everything=1